#!/usr/bin/env bash

if [ ! -d "src" ] || [ ! -f "src/Makefile" ]; then
	echo "please execute in the top level directory; where src/ is"
	exit 1;
fi

if [ -z "$SHELL" ]; then
	echo "WARNING: \$SHELL not set, using bash"
	SHELL_EXE="bash";
else
	SHELL_EXE="$SHELL";
fi

if [ ! -z "$CAD_FOR_DIGITAL_BANDB_ROOTDIR" ]; then
	echo "WARNING: invocation from already initialized environment. Old CAD_FOR_DIGITAL_BANDB_ROOTDIR=$CAD_FOR_DIGITAL_BANDB_ROOTDIR";
fi

export CAD_FOR_DIGITAL_BANDB_ROOTDIR="$(readlink --canonicalize "$PWD")/";
export CAD_FOR_DIGITAL_BANDB_EXEDIR="$CAD_FOR_DIGITAL_BANDB_ROOTDIR/build/EXE/";
export CAD_FOR_DIGITAL_BANDB_SCRIPTSDIR="$CAD_FOR_DIGITAL_BANDB_ROOTDIR/scripts/";
export CAD_FOR_DIGITAL_BANDB_DATADIR="$CAD_FOR_DIGITAL_BANDB_ROOTDIR/data/";

export PATH="$PATH:$CAD_FOR_DIGITAL_BANDB_EXEDIR:$CAD_FOR_DIGITAL_BANDB_SCRIPTSDIR"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$(readlink --canonicalize ./SuiteSparse/lib)"

echo "Entering $SHELL_EXE with setup environment. CAD_FOR_DIGITAL_BANDB_ROOTDIR=$CAD_FOR_DIGITAL_BANDB_ROOTDIR";
$SHELL_EXE
echo "Exiting environment. Old CAD_FOR_DIGITAL_BANDB_ROOTDIR=$CAD_FOR_DIGITAL_BANDB_ROOTDIR";
